version: '3.8'

services:
  django:
    container_name: dj
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 8001"
    ports:
      - "8044:8001"
    env_file:
      - .env
    depends_on:
      - pgdata
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9010:9000"
      - "9020:9001"
    env_file:
      - .env
    command: server /export --console-address :9001

  pgdata:
    container_name: pg
    image: postgres:alpine
    ports:
      - "5435:5432"
    env_file:
      - .env
    volumes:
      - pg_volume:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - django

volumes:
  pg_volume:
  static_volume:
  media_volume: